### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by boensu452** [ethersphere/bee-dashboard#134]
/usr/lib/node_modules/@ethersphere/bee-dashboard/node_modules/serve-handler/src/index.js:194
const getHeaders = async (handlers, config, current, absolutePath, stats) => {
                         ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@ethersphere/bee-dashboard/serve.js:4:17)

**Comment by vojtechsimetka** [comment]
Thanks for reporting. Which OS are you running this on?

**Comment by vojtechsimetka** [comment]
Since we have not hear more such reports I am closing this issue
